package org.jetbrains.reflekt

/**
 * Marks declarations that are **internal** in Reflekt API, which means that should not be used outside of code or IR generated by Reflekt or Reflekt's testing
 * files.
 */
@Retention(value = AnnotationRetention.BINARY)
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.TYPEALIAS,
    AnnotationTarget.PROPERTY,
    AnnotationTarget.CONSTRUCTOR,
)
@RequiresOptIn(
    level = RequiresOptIn.Level.ERROR,
    message = "This is an internal Reflekt API that should not be used outside of code or IR generated by Reflekt or Reflekt's testing files",
)
annotation class InternalReflektApi
