name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set up JDK 11
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 11
          distribution: liberica
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.1.0
      - uses: gradle/gradle-build-action@v2.7.1
        with:
          arguments: detekt --stacktrace
