name: Run deteKT

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  detekt_check:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.5.2
      - name: Set up JDK 11
        uses: actions/setup-java@v3.11.0
        with:
          java-version: 11
          distribution: liberica
      - uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: detekt --stacktrace
      - uses: github/codeql-action/upload-sarif@v2
        if: ${{ always() }}
        with:
          sarif_file: ./build/reflekt/reports/detekt/merge.sarif
          category: detekt
