name: Gradle Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3.0.2
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 11
          distribution: liberica
      - uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: build --stacktrace
      - name: Upload Test Report
        uses: actions/upload-artifact@v3.1.0
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            reflekt-plugin/build/reports/tests/**/*
