name: Kotlin build

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      # Setup Java 11 environment for the next steps
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 11

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: ctions/setup-java@v3.4.0
        with:
          java-version: 11

      - uses: actions/checkout@v3.0.2
      - run: ./gradlew build -x test

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Setup Java 11 environment for the next steps
      - name: Setup Java
        uses: ctions/setup-java@v3.4.0
        with:
          java-version: 11
      - uses: actions/checkout@v3.0.2
      - run: ./gradlew test
      - name: Upload Test Report
        uses: actions/upload-artifact@v3.1.0
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            reflekt-plugin/build/reports/tests/**/*  
