

package org.jetbrains.reflekt.plugin.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link GenerateNewCompilerTests.kt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("reflekt-plugin/src/test/resources/org/jetbrains/reflekt/plugin/compiler/code-gen/helpers-test")
@TestDataPath("$PROJECT_ROOT")
public class HelpersTestGenerated extends AbstractHelpersTest {
    @Test
    public void testAllFilesPresentInHelpers_test() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("reflekt-plugin/src/test/resources/org/jetbrains/reflekt/plugin/compiler/code-gen/helpers-test"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("simple.kt")
    public void testSimple() throws Exception {
        runTest("reflekt-plugin/src/test/resources/org/jetbrains/reflekt/plugin/compiler/code-gen/helpers-test/simple.kt");
    }

    @Test
    @TestMetadata("simple-helpers.kt")
    public void testSimple_helpers() throws Exception {
        runTest("reflekt-plugin/src/test/resources/org/jetbrains/reflekt/plugin/compiler/code-gen/helpers-test/simple-helpers.kt");
    }
}
